spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/flower_shop}?useUnicode=true&characterEncoding=utf8
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    show-sql: true

server:
  port: 8082